In [6]:
from array import array

import numpy as np
np.random.seed(0)

x2 = np.random.randint(10, size=(3, 4))

print (x2)
#x1 = array([[3, 5, 2, 4], [7, 6, 8, 8], [1, 6, 7, 7]])
#x1

x2[2,0]

x2[:]


[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


(3,)

In [12]:
x = np.array([1, 2, 3])
x.shape

(3,)

In [17]:
x = x.reshape((1, 3))
x.shape

(1, 3)

In [18]:
x


array([[1, 2, 3]])